name: flutter_rating_bar
description: A simple yet fully customizable ratingbar for flutter which also include a rating bar indicator, supporting any fraction of rating.
version: 4.0.0-nullsafety.0
repository: https://github.com/sarbagyastha/flutter_rating_bar
homepage: https://sarbagyastha.com.np

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: '>=1.12.13+hotfix.5 <2.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
